
'use client';

import { Button } from '@/components/ui/button';
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { CheckCircle, LayoutGrid, XCircle, Zap } from 'lucide-react';
import Image from 'next/image';
import Link from 'next/link';
import React, { useRef } from 'react';
import { useMounted } from '@/hooks/use-mounted';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import {
  Carousel,
  CarouselContent,
  CarouselItem,
} from '@/components/ui/carousel';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import Autoplay from 'embla-carousel-autoplay';

const featureCards = [
  {
    icon: <Zap className="h-8 w-8 text-accent" />,
    title: 'Fast & Efficient',
    description: 'Generate comprehensive business plans and documents in minutes, not weeks.',
  },
  {
    icon: <LayoutGrid className="h-8 w-8 text-accent" />,
    title: 'All-in-One Suite',
    description: 'From idea validation to financial planning, get all the tools you need under one roof.',
  },
  {
    icon: <CheckCircle className="h-8 w-8 text-accent" />,
    title: 'Data-Driven Insights',
    description: 'Leverage AI analysis of the Mauritian market to make smarter business decisions.',
  },
    {
    icon: <LayoutGrid className="h-8 w-8 text-accent" />,
    title: 'Investor-Ready',
    description: 'Produce professional, investor-ready documents to secure funding for your venture.',
  },
];

const testimonials = [
    {
        quote: "StudioFlow AI transformed my vision of creating, launching, and managing a business in Mauritius. The insights from the idea validation were pure gold. One can go from a vague concept to an investor-ready plan in less than a week.",
        author: "Wesley R.",
        title: "Founder of Affilia Ltd",
        avatar: "/images/wr.png"
    },
    {
        quote: "As a solo founder, the budget planner and MVP roadmap were lifesavers. It felt like having a co-founder who's an expert in finance and product.",
        author: "Stephan T.",
        title: "Owner of Tourmentin Marketing",
        avatar: "/images/st.png"
    },
    {
        quote: "The most comprehensive startup tool for the Mauritian market. Period. The localization of the AI's analysis is what sets it apart.",
        author: "Dona M.",
        title: "Sales Tech at FIDS Ltd.",
        avatar: "/images/dm.png"
    },
    {
        quote: "We secured our pre-seed funding using the business plan generated by this platform. The financial projections were spot-on and gave our investors confidence.",
        author: "Jean-Marc P.",
        title: "Co-founder, FinTech Innovators",
        avatar: "/images/image1-5.png"
    },
    {
        quote: "This is not just a tool; it's a mentor. It guides you, asks the right questions, and forces you to think critically about every aspect of your business.",
        author: "Laura M.",
        title: "Wellness-preneurs Mauritius",
        avatar: "/images/image1-0.png"
    },
     {
        quote: "The ability to go from a simple idea to a full PRD is incredible. It streamlined our entire product development process and saved us countless hours.",
        author: "Katherina S.",
        title: "Product Lead, AppFactory",
        avatar: "/images/image1-99.png"
    }
]

export default function Home() {
  const isMounted = useMounted();
  const plugin = useRef(
    Autoplay({ delay: 3000, stopOnInteraction: true })
  )

  if (!isMounted) {
    return null;
  }
  
  return (
    <div className="flex flex-col min-h-screen bg-background text-primary-foreground">
      <header className="sticky top-0 z-50 w-full bg-secondary/80 backdrop-blur-sm">
        <div className="container mx-auto flex h-16 items-center justify-between px-4 md:px-6">
          <Link href="/" className="flex items-center gap-2">
            <LayoutGrid className="h-8 w-8 text-primary" />
            <span className="text-xl font-bold">StudioFlow AI</span>
          </Link>
          <nav className="hidden items-center gap-6 md:flex">
            <Link href="#features" className="text-sm font-medium hover:text-primary">
              Features
            </Link>
            <Link href="#pricing" className="text-sm font-medium hover:text-primary">
              Pricing
            </Link>
             <Dialog>
              <DialogTrigger asChild>
                <button className="text-sm font-medium hover:text-primary">Contact</button>
              </DialogTrigger>
              <DialogContent className="sm:max-w-[425px]">
                <DialogHeader>
                  <DialogTitle>Contact Us</DialogTitle>
                  <DialogDescription>
                    Have a question or want to work with us? Fill out the form below.
                  </DialogDescription>
                </DialogHeader>
                <div className="grid gap-4 py-4">
                  <div className="grid grid-cols-4 items-center gap-4">
                    <Label htmlFor="name" className="text-right">
                      Name
                    </Label>
                    <Input id="name" placeholder="John Doe" className="col-span-3" />
                  </div>
                  <div className="grid grid-cols-4 items-center gap-4">
                    <Label htmlFor="email" className="text-right">
                      Email
                    </Label>
                    <Input id="email" type="email" placeholder="john@example.com" className="col-span-3" />
                  </div>
                   <div className="grid grid-cols-4 items-start gap-4">
                    <Label htmlFor="message" className="text-right pt-2">
                      Message
                    </Label>
                    <Textarea id="message" placeholder="Your message..." className="col-span-3" />
                  </div>
                </div>
                <DialogFooter>
                  <Button type="submit">Send Message</Button>
                </DialogFooter>
              </DialogContent>
            </Dialog>
          </nav>
          <Button asChild variant="ghost">
            <Link href="/login">Sign In</Link>
          </Button>
        </div>
      </header>

      <main className="flex-1">
        {/* Hero Section */}
        <section className="bg-primary flex items-center min-h-screen relative overflow-hidden">
          <div
            className="absolute inset-0 bg-cover bg-center opacity-40"
            style={{ backgroundImage: 'url(/images/hero_bk2.webp)' }}
          ></div>
          <div className="container relative z-10 mx-auto grid grid-cols-1 md:grid-cols-2 items-center gap-8 px-4 py-20 text-center md:text-left">
            <div className="relative z-20 space-y-6">
              <h1 className="text-4xl font-bold tracking-tight md:text-5xl lg:text-6xl">
                The Future of Business Creation <br /> is Here
              </h1>
              <p className="max-w-xl text-lg text-primary-foreground/80 mx-auto md:mx-0">
                StudioFlow AI is your unified command center for launching and managing your business in Mauritius. Leverage our AI-powered suite to go from idea to investor-ready, faster than ever before.
              </p>
              <div className="flex flex-col gap-4 sm:flex-row sm:justify-center md:justify-start">
                <Button size="lg" asChild className="bg-accent hover:bg-accent/90 text-accent-foreground">
                  <Link href="#pricing">Let's get Started</Link>
                </Button>
                <Button size="lg" asChild className="bg-secondary text-secondary-foreground hover:bg-secondary/90">
                  <Link href="/login">Login</Link>
                </Button>
              </div>
            </div>
            <div className="relative z-10">
                <Image 
                    src="/images/AI-FirstBusiness.webp"
                    width={780}
                    height={780}
                    alt="AI First Business Illustration"
                    className="mx-auto animate-float"
                    data-ai-hint="futuristic business illustration"
                />
            </div>
          </div>
        </section>

        {/* Features Section */}
        <section id="features" className="bg-secondary py-20 lg:py-32">
          <div className="container mx-auto px-4">
            <div className="mx-auto max-w-3xl text-center">
              <h2 className="text-3xl font-bold tracking-tight md:text-4xl">
                Grab that Unique, Unfair Advantage...
              </h2>
              <p className="mt-4 text-lg text-primary-foreground/70">
                Condense weeks of research, planning, and paperwork into a few guided sessions. Our AI agents are trained to help you succeed within minutes.
              </p>
            </div>
            <div className="mt-12 grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-4">
              {featureCards.map((feature) => (
                <Card key={feature.title} className="bg-card text-card-foreground">
                  <CardHeader>
                    {feature.icon}
                    <CardTitle className="mt-4">{feature.title}</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-muted-foreground">{feature.description}</p>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </section>

        {/* Brilliant Tools Section */}
        <section id="whatis" className="bg-secondary-darker py-20 lg:py-32">
            <div className="container mx-auto grid grid-cols-1 items-center gap-12 px-4 md:grid-cols-2">
                <div>
                     <Image
                        src="/images/app_gallery_3.webp"
                        width={550}
                        height={550}
                        alt="Tool Illustrations"
                        data-ai-hint="abstract tool illustration"
                        className="mx-auto rounded-lg"
                    />
                </div>
                <div className="space-y-6">
                    <h2 className="text-3xl font-bold tracking-tight md:text-4xl">Brilliant tools that get you results</h2>
                    <p className="text-lg text-primary-foreground/70">
                        From validating your business idea against the local market to generating a full-fledged financial plan and investor-ready business plan, our suite is designed to give you the clarity and confidence to launch.
                    </p>
                    <ul className="space-y-4">
                        <li className="flex items-start gap-3">
                            <CheckCircle className="h-6 w-6 flex-shrink-0 text-accent" />
                            <span><span className="font-semibold">Idea Validation:</span> Get AI-powered feedback on your concept's viability in Mauritius.</span>
                        </li>
                         <li className="flex items-start gap-3">
                            <CheckCircle className="h-6 w-6 flex-shrink-0 text-accent" />
                            <span><span className="font-semibold">MVP & Budget Planning:</span> Map out your product, costs, and break-even point with precision.</span>
                        </li>
                         <li className="flex items-start gap-3">
                            <CheckCircle className="h-6 w-6 flex-shrink-0 text-accent" />
                            <span><span className="font-semibold">Full Business Plan:</span> Synthesize all your work into a single, professional document ready for funding.</span>
                        </li>
                    </ul>
                </div>
            </div>
        </section>

        {/* Pricing Section */}
        <section id="pricing" className="bg-secondary py-20 lg:py-32">
            <div className="container mx-auto px-4 text-center">
                 <h2 className="text-3xl font-bold tracking-tight md:text-4xl">Pricing Plans</h2>
                 <p className="mt-4 max-w-2xl mx-auto text-lg text-primary-foreground/70">
                    Choose a plan that scales with your ambition. Start for free and upgrade as your business grows.
                 </p>
                 <div className="mt-12 grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-4">
                     {/* Free Plan */}
                     <Card className="bg-card text-card-foreground p-6 flex flex-col">
                         <CardHeader>
                            <CardTitle>Test Drive</CardTitle>
                            <p className="text-4xl font-bold mt-2">MUR 0</p>
                         </CardHeader>
                         <CardContent className="flex-grow space-y-4 text-left">
                            <p>For entrepreneurs and Business owners who want get a feel of StudioFlow.</p>
                             <ul className="space-y-2">
                                <li className="flex items-center gap-2"><CheckCircle className="text-accent h-5 w-5"/> 1 Business Project</li>
                                <li className="flex items-center gap-2"><CheckCircle className="text-accent h-5 w-5"/> 1 seat</li>
                                <li className="flex items-center gap-2"><XCircle className="text-destructive h-5 w-5"/> No Reporting</li>
                                <li className="flex items-center gap-2"><XCircle className="text-destructive h-5 w-5"/> No Document Downloads</li>
                             </ul>
                         </CardContent>
                         <Button asChild variant="outline" className="w-full mt-6">
                            <Link href="/login?redirect=/business-management">Get Started</Link>
                         </Button>
                     </Card>
                     {/* Business Tool Kits */}
                     <Card className="bg-primary text-primary-foreground p-6 flex flex-col ring-2 ring-accent">
                         <CardHeader>
                            <CardTitle>Business Tool Kits</CardTitle>
                            <p className="text-4xl font-bold mt-2">MUR 200/mth<span className="text-lg font-normal text-primary-foreground/70">/seat</span></p>
                         </CardHeader>
                         <CardContent className="flex-grow space-y-4 text-left">
                            <p>For entrepreneurs and startups who need specific tools to operate smartly.</p>
                             <ul className="space-y-2">
                                <li className="flex items-center gap-2"><CheckCircle className="h-5 w-5"/> Choose 1 re-usable tool</li>
                                <li className="flex items-center gap-2"><CheckCircle className="h-5 w-5"/> up to 5 seats</li>
                                <li className="flex items-center gap-2"><CheckCircle className="h-5 w-5"/> Industry Standard Reports</li>
                                <li className="flex items-center gap-2"><CheckCircle className="h-5 w-5"/> Uploadable PDFs </li>
                                <li className="flex items-center gap-2"><CheckCircle className="h-5 w-5"/> Comprehensive Dashboard</li>
                             </ul>
                         </CardContent>
                         <Button className="w-full mt-6 bg-accent hover:bg-accent/90 text-accent-foreground">Choose your tool today</Button>
                     </Card>
                     {/* Pro */}
                     <Card className="bg-primary text-primary-foreground p-6 flex flex-col ring-2 ring-accent">
                         <CardHeader>
                            <CardTitle>PRO</CardTitle>
                            <p className="text-4xl font-bold mt-2">MUR 400/mth<span className="text-lg font-normal text-primary-foreground/70">/seat</span></p>
                         </CardHeader>
                         <CardContent className="flex-grow space-y-4 text-left">
                            <p>For serious Business Owners and Executives and team members.</p>
                             <ul className="space-y-2">
                                <li className="flex items-center gap-2"><CheckCircle className="h-5 w-5"/> Unlimited Business Ideas Validation</li>
                                <li className="flex items-center gap-2"><CheckCircle className="h-5 w-5"/> up to 4 seats</li>
                                <li className="flex items-center gap-2"><CheckCircle className="h-5 w-5"/> Full Business Creation Suite</li>
                                <li className="flex items-center gap-2"><CheckCircle className="h-5 w-5"/> Financial Planning Tools</li>
                                <li className="flex items-center gap-2"><CheckCircle className="h-5 w-5"/> Advanced Reporting</li>
                             </ul>
                         </CardContent>
                         <Button className="w-full mt-6 bg-accent hover:bg-accent/90 text-accent-foreground">Choose Pro</Button>
                     </Card>
                     {/* Enterprise Plan */}
                     <Card className="bg-card text-card-foreground p-6 flex flex-col">
                         <CardHeader>
                            <CardTitle>AI Transformation Blueprints</CardTitle>
                             <p className="text-4xl font-bold mt-2">Contact Us</p>
                         </CardHeader>
                         <CardContent className="flex-grow space-y-4 text-left">
                            <p>For established companies and agencies who need to implement reliable AI-driven tools, protocols and workflows in-house.</p>
                             <ul className="space-y-2">
                                <li className="flex items-center gap-2"><CheckCircle className="text-accent h-5 w-5"/> Holistic Future-proof Approach</li>
                                <li className="flex items-center gap-2"><CheckCircle className="text-accent h-5 w-5"/> Technical and Practical Roadmaps</li>
                                <li className="flex items-center gap-2"><CheckCircle className="text-accent h-5 w-5"/> Training Curriculums</li>
                                <li className="flex items-center gap-2"><CheckCircle className="text-accent h-5 w-5"/> Custom Integrations</li>
                             </ul>
                         </CardContent>
                         <Button variant="outline" className="w-full mt-6">Contact Sales</Button>
                     </Card>
                 </div>
            </div>
        </section>
        
        {/* Testimonials Section */}
        <section id="testimonials" className="bg-secondary-darker py-20 lg:py-32">
            <div className="container mx-auto px-4 text-center">
                <h2 className="text-3xl font-bold tracking-tight md:text-4xl">Trusted by Innovators</h2>
                <p className="mt-4 max-w-2xl mx-auto text-lg text-primary-foreground/70">
                    Don't just take our word for it. Here's what founders and business owners are saying about StudioFlow AI.
                </p>
                <Carousel
                    plugins={[plugin.current]}
                    className="w-full mt-12"
                    onMouseEnter={plugin.current.stop}
                    onMouseLeave={plugin.current.reset}
                     opts={{
                        align: "start",
                        loop: true,
                    }}
                >
                    <CarouselContent>
                        {testimonials.map((testimonial, index) => (
                            <CarouselItem key={index} className="md:basis-1/2 lg:basis-1/3">
                                <div className="p-1 h-full">
                                    <Card className="bg-muted/50 text-card-foreground border-2 border-primary/20 h-full flex flex-col p-6 rounded-lg">
                                        <CardContent className="p-0 flex-grow text-left">
                                            <p className="text-base text-foreground/80">"{testimonial.quote}"</p>
                                        </CardContent>
                                        <CardFooter className="p-0 pt-6 mt-auto flex items-center gap-4">
                                            <Avatar className="h-16 w-16">
                                                <AvatarImage src={testimonial.avatar} alt={testimonial.author} />
                                                <AvatarFallback>{testimonial.author.charAt(0)}</AvatarFallback>
                                            </Avatar>
                                            <div className="text-left">
                                                <p className="font-bold text-lg text-foreground">{testimonial.author}</p>
                                                <p className="text-sm text-muted-foreground">{testimonial.title}</p>
                                            </div>
                                        </CardFooter>
                                    </Card>
                                </div>
                            </CarouselItem>
                        ))}
                    </CarouselContent>
                </Carousel>
            </div>
        </section>
      </main>

      <footer className="bg-primary text-primary-foreground">
        <div className="container mx-auto grid grid-cols-2 gap-8 px-4 py-12 md:grid-cols-5">
            <div className="col-span-2 md:col-span-1">
                 <Link href="/" className="flex items-center gap-2">
                    <LayoutGrid className="h-8 w-8 text-accent" />
                    <span className="text-xl font-bold">StudioFlow AI</span>
                </Link>
                <p className="mt-4 text-sm text-primary-foreground/60">The future of business creation.</p>
            </div>
            <div>
                <h4 className="font-semibold">Product</h4>
                <ul className="mt-4 space-y-2 text-sm">
                    <li><Link href="#features" className="text-primary-foreground/60 hover:text-primary-foreground">Features</Link></li>
                    <li><Link href="#pricing" className="text-primary-foreground/60 hover:text-primary-foreground">Pricing</Link></li>
                    <li><Link href="#" className="text-primary-foreground/60 hover:text-primary-foreground">Updates</Link></li>
                </ul>
            </div>
            <div>
                <h4 className="font-semibold">Company</h4>
                <ul className="mt-4 space-y-2 text-sm">
                    <li><Link href="#" className="text-primary-foreground/60 hover:text-primary-foreground">About</Link></li>
                    <li><Link href="#" className="text-primary-foreground/60 hover:text-primary-foreground">Careers</Link></li>
                    <li><Link href="#" className="text-primary-foreground/60 hover:text-primary-foreground">Contact</Link></li>
                </ul>
            </div>
            <div>
                <h4 className="font-semibold">Resources</h4>
                <ul className="mt-4 space-y-2 text-sm">
                    <li><Link href="#" className="text-primary-foreground/60 hover:text-primary-foreground">Blog</Link></li>
                    <li><Link href="#" className="text-primary-foreground/60 hover:text-primary-foreground">Help Center</Link></li>
                    <li><Link href="#" className="text-primary-foreground/60 hover:text-primary-foreground">Privacy Policy</Link></li>
                </ul>
            </div>
             <div>
                <h4 className="font-semibold">Social</h4>
                <ul className="mt-4 space-y-2 text-sm">
                    <li><Link href="https://x.com/AlainBertrandmu/" className="text-primary-foreground/60 hover:text-primary-foreground" target="_blank" rel="noopener noreferrer">Twitter</Link></li>
                    <li><Link href="https://www.linkedin.com/company/avantaz/" className="text-primary-foreground/60 hover:text-primary-foreground" target="_blank" rel="noopener noreferrer">LinkedIn</Link></li>
                    <li><Link href="https://www.facebook.com/avantaz.mu" className="text-primary-foreground/60 hover:text-primary-foreground" target="_blank" rel="noopener noreferrer">Facebook</Link></li>
                </ul>
            </div>
        </div>
        <div className="container mx-auto border-t border-primary-foreground/10 px-4 py-6 text-center text-sm text-primary-foreground/60">
           © 2025 StudioFlow AI (Alain BERTRAND). All rights reserved.
        </div>
      </footer>
    </div>
  );
}
